// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local (Next.js convention), then .env as fallback
dotenv.config({ path: ".env.local", override: true });
dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations prefer DIRECT_URL (direct 5432 connection that supports the
    // shadow database + schema introspection). Falls back to DATABASE_URL for
    // envs where only one connection string is available.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
